Add option "required" to builder configs which will cause rosdoc_lite to fail if the builder fails.
ros-infrastructure/rosdoc_lite pull request #106
Opened 2023-05-01 18:04 UTC by peci1

Resolves #63.

Each builder gets an optional parameter `required`. If set to True, rosdoc_lite will fail if the builder failed. However, all other builders are given the option to finish their run before rosdoc_lite is exited, so that as much documentation is generated as possible.

I've set the parameter to default to False so that the feature is opt-in. This should leave all existing packages without a change, but new packages are allowed to opt in. We could also change the documentation to consistently add `required: True` in the examples, with the note that it can be turned off.

@tfoote Would this be a good approach?

2023-05-01 23:05 UTC, tfoote requested changes
Overall this looks like a good way to enable this. 

I had one code comment. The documentation for generate_docs should be extended to document the potential exception in the doc block. 

And I'd like to see a little bit more added to the documentation to document this capability. But overall this looks like a great addition.

2023-05-01 23:32 UTC, peci1 commented
Thanks for the review. I've updated the code docs a bit. However, the main documentation is on the Wiki, which I'll update when this PR is merged.

2023-06-23 21:38 UTC, tfoote approved these changes
This looks good to me. Thanks for the iteration.

2023-06-23 21:41 UTC, merged

2023-06-25 08:29 UTC, peci1 commented
With no outsanding PRs, would it be a good time to make a release?

2023-06-25 08:37 UTC, peci1 commented
Wiki docs updated: http://wiki.ros.org/action/info/rosdoc_lite?action=diff&rev2=24&rev1=23 .